README.md
packages/backend/package.json
packages/frontend/README.md
packages/frontend/package.json
packages/frontend/public/index.html
packages/infra/cdk.json
packages/infra/cdk/aws-sdk-js-notes-app-stack.ts
packages/infra/cdk/aws-sdk-js-notes-app.ts
packages/infra/cdk/aws-sdk-js-todo-app.ts
packages/infra/package.json
packages/scripts/populate-frontend-config.js
yarn.lock

N/A
Rename todo-app to notes-app.
The original plan was to create a ToDo app, as it is most common apps to start with. But we'll stick with Notes app as of now
Verified that backend, frontend and infra are working fine.
---

chore: rename todo-app to notes-app

---

packages/backend/README.md
packages/frontend/README.md
packages/frontend/src/config.json
packages/frontend/src/libs/s3Client.ts
packages/infra/cdk/aws-sdk-js-notes-app-stack.ts
packages/scripts/populate-frontend-config.js

N/A
The region was hardcoded in frontend s3Client. This PR makes region configurable, and it's read from the output of infrastructure code.
Verified that frontend works in local run.
---

feat(frontend): read region from config 

---

packages/frontend/src/content/RecordAudioButton.tsx

Fixes: https://github.com/aws-samples/aws-sdk-js-notes-app/issues/11
Uses temporary variable to store transcriptions, and removes partial transcriptions from the state.
<details>
<summary>Screen recording</summary>
https://user-images.githubusercontent.com/16024985/106825138-110a7880-6639-11eb-9a23-faf915fe4d44.mov
</details>
---

fix: use temporary variable to store partial transcriptions

---

packages/frontend/src/content/CreateNote.tsx
packages/frontend/src/content/RecordAudioButton.tsx

Follow-up to https://github.com/aws-samples/aws-sdk-js-notes-app/pull/14
Clean up the following eslint warnings in RecordAudioButton:
```console
Compiled with warnings.
src/content/RecordAudioButton.tsx
Line 17:40:  'noteContent' is assigned a value but never used                                       @typescript-eslint/no-unused-vars
Line 88:17:  Function declared in a loop contains unsafe references to variable(s) 'transcription'  no-loop-func
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```
Verified that real-time audio transcription works, and no warnings are shown in console.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

chore: clean up eslint warnings in RecordAudioButton

---

packages/frontend/src/libs/audioUtils.ts

N/A
The original pcmEncode function was picked up from: https://github.com/amazon-archives/amazon-transcribe-websocket-static/blob/6a0b97f1c667b649c31cd9b550c37795a5c7ce25/lib/audioUtils.js#L1-L10
This PR cleans it up by using let/const instead of var, and removing redundant variables.
Verified that real-time audio transcription works.
---

chore: clean-up pcmEncode utility function

---

packages/frontend/package.json
packages/frontend/src/content/RecordAudioButton.tsx
yarn.lock

Consume microphone-stream type definitions added in https://github.com/saebekassebil/microphone-stream/pull/40
Consume type definitions added in `microphone-stream@5.2.0` and remove `any`
Verified that real-time audio transcription is working.
---

chore: consume types from microphone-stream package

---

packages/infra/package.json
yarn.lock

To try nodejs14.x runtime on lambda introduced in aws-cdk 1.89.0 https://github.com/aws/aws-cdk/pull/12861
bumps cdk to 1.89.0
```console
$ yarn cdk diff
Stack aws-sdk-js-notes-app
There were no differences
```
---

chore(deps-dev): bump aws-cdk to 1.89.0

---

packages/infra/cdk/notes-api.ts

[aws-cdk@1.89.0](https://github.com/aws/aws-cdk/releases/tag/v1.89.0) now supports nodejs14.x runtime in lambda.
Upgrades version of Node.js runtime to latest LTS 14.x in Lambda.
Verified that notes-app is working as designed.
<details>
<summary>yarn cdk diff</summary>
```console
Stack aws-sdk-js-notes-app
Resources
[~] AWS::Lambda::Function listNotes/handler listNoteshandlerDC187D34 
└─ [~] Runtime
├─ [-] nodejs12.x
└─ [+] nodejs14.x
[~] AWS::Lambda::Function createNote/handler createNotehandlerBA768AA5 
└─ [~] Runtime
├─ [-] nodejs12.x
└─ [+] nodejs14.x
[~] AWS::Lambda::Function getNote/handler getNotehandler167C5FCF 
└─ [~] Runtime
├─ [-] nodejs12.x
└─ [+] nodejs14.x
[~] AWS::Lambda::Function updateNote/handler updateNotehandler6A5A41DF 
└─ [~] Runtime
├─ [-] nodejs12.x
└─ [+] …
```

feat(backend): use nodejs14.x runtime in lambdas

---

packages/infra/package.json
yarn.lock

N/A
Bump aws-cdk to 1.115.0
Deployed backend, and verified there's no diff
---

chore(deps-dev): bump aws-cdk to 1.115.0

---

packages/frontend/index.html
packages/frontend/package.json
packages/frontend/src/index.tsx
packages/frontend/tsconfig.json
packages/frontend/vite.config.ts
yarn.lock

N/A
Replaces create-react-app with vite to use fast development builds using esbuild.
<details>
<summary>Before</summary>
```console
$ yarn start
...
takes 10+ seconds
$ time yarn build
Creating an optimized production build...
...
yarn build  71.85s user 7.81s system 179% cpu 44.387 total
```
</details>
<details>
<summary>After</summary>
```console
$ yarn start
vite v2.4.4 dev server running at:
> Local: http://localhost:3000/
> Network: use `--host` to expose
ready in 1255ms.
$ time yarn build
vite v2.4.4 building for production...
...
yarn build  32.71s user 1.98s system 202% cpu 17.145 total
```
</details>
Local testing for the following commands:
* `yarn start`
* `yarn build`
* `yarn serve`
---
By submitting this pull request, I confirm that you can use, modify, copy, and …

feat: replace react-scripts with vite

---

packages/infra/cdk/aws-sdk-js-notes-app-stack.ts

Refs: https://github.com/aws-samples/aws-sdk-js-notes-app/issues/21
Remove redundant mention of default DESTROY [removalPolicy](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.RemovalPolicy.html#destroy)
Local testing.
---

chore(infra): remove redundant default DESTROY removalPolicy

---

packages/backend/build.js

Follow-up to https://github.com/aws-samples/aws-sdk-js-notes-app/pull/40
Enable tree shaking in ESBuild by preferring `module` field before `main`.
Docs: https://esbuild.github.io/api/#main-fields
<details>
<summary>Before</summary>
```console
$ yarn build:backend
dist/updateNote/app.js  498.4kb
dist/createNote/app.js  498.4kb
dist/getNote/app.js     498.3kb
dist/deleteNote/app.js  498.3kb
dist/listNotes/app.js   498.2kb
⚡ Done in 102ms
```
</details>
<details>
<summary>After</summary>
```console
$ yarn build:backend
dist/updateNote/app.js  243.0kb
dist/createNote/app.js  242.8kb
dist/deleteNote/app.js  242.4kb
dist/getNote/app.js     240.6kb
dist/listNotes/app.js   238.5kb
⚡ Done in 107ms
```
</details>
Verified that notes application works.
---
By submitting this pull request, I confirm …

fix(backend): enable tree shaking in esbuild

---

packages/infra/cdk.json
packages/infra/package.json
packages/infra/tsconfig.json

Fixes: https://github.com/aws-samples/aws-sdk-js-notes-app/issues/46
Refs: https://github.com/TypeStrong/ts-node/issues/1427
Removes dependency on ts-node, so that it doesn't blocker in the infrastructure deployment.
The infrastructure script transpiles TS to JS before calling cdk.
Verified that cdk commands are successful
---

chore(infra): remove dependency on ts-node

---

yarn.lock

Fixes: https://github.com/aws-samples/aws-sdk-js-notes-app/issues/51
Refs:
* https://github.com/aws/aws-cdk/issues/12536#issuecomment-774678334
* https://github.com/serverless/serverless/issues/8772#issuecomment-825698908
Bump crc32-stream to v4.0.2
Verified that CDK deployments are successful.
---

chore(deps-dev): bump crc32-stream to v4.0.2

---

packages/infra/package.json
yarn.lock

Bump aws-cdk to v1.132.0
CDK deployments were successful.
---

chore(deps-dev): bump aws-cdk to v1.132.0

---

packages/backend/package.json
packages/frontend/package.json
packages/infra/package.json
yarn.lock

Bump typescript to ~4.4.4
Builds are successful for frontend and backend.
CDK deployment is successful
---

chore(deps-dev): bump typescript to ~4.4.4

---

package.json
packages/backend/.eslintrc.json
packages/backend/package.json
yarn.lock

Bumps eslint to 8.x
Verified that eslint runs in the backend package
```console
$ ../../node_modules/.bin/eslint --fix-dry-run src/**/*.ts
/Users/trivikr/workspace/aws-sdk-js-notes-app/packages/backend/src/libs/response.ts
1:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
5:31  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
9:50  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
✖ 3 problems (0 errors, 3 warnings)
```
---

chore(deps-dev): bump eslint to 8.x

---

packages/infra/cdk/aws-sdk-js-notes-app-stack.ts
packages/infra/cdk/aws-sdk-js-notes-app.ts
packages/infra/cdk/notes-api.ts
packages/infra/package.json
yarn.lock

Fixes: https://github.com/aws-samples/aws-sdk-js-notes-app/issues/61
Bumps cdk to v2.0.0
Local testing by following README
---

chore(deps-dev): bump to cdk 2.0.0

---

README.md
packages/backend/build.js
packages/backend/package.json
packages/frontend/package.json
packages/infra/package.json
yarn.lock

* Node.js 16 went LTS on 2021-10-26 https://nodejs.org/en/about/releases/
* We bumped Lambda to Node.js 16.x https://github.com/aws-samples/aws-sdk-js-notes-app/pull/67
Recommend Node.js 16.x
Local testing
---

chore: recommend Node.js 16.x

---

packages/frontend/package.json
packages/frontend/src/index.tsx
yarn.lock

Refs: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
Uses client rendering APIs from React 18.
Local testing
---

chore(frontend): use createRoot from React 18

---

packages/frontend/package.json
yarn.lock

Vite 3.0 is out https://vitejs.dev/blog/announcing-vite3.html
Bumps vite to 3.0.0
ToDo: Local testing
Migration Guide https://vitejs.dev/guide/migration.html
---

feat(deps): bump vite to 3.2.5

---

packages/infra/package.json
yarn.lock

Similar to https://github.com/aws-samples/aws-sdk-js-notes-app/pull/66
Bumps aws-cdk to 2.59.0
Verified that `yarn cdk deploy` works
---

chore(deps-dev): bump aws-cdk to 2.59.0

---

packages/infra/cdk/notes-api.ts

Follow-up to https://github.com/aws-samples/aws-sdk-js-notes-app/pull/67
Lambda added support for Node.js 18.x https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
Bump Lambda Runtime to NODEJS_18_X
Verified that backend is deployed on Node.js 18 functions, and works with frontend.
---

chore(infra): bump Lambda Runtime to NODEJS_18_X

---

README.md
packages/backend/build.js
packages/backend/package.json
packages/frontend/package.json
packages/infra/package.json
yarn.lock

Follow-up to https://github.com/aws-samples/aws-sdk-js-notes-app/pull/68
* Node.js 18.x went LTS on 2022-10-25 https://github.com/nodejs/release#release-schedule
* We bumped Lambda to Node.js 18.x in https://github.com/aws-samples/aws-sdk-js-notes-app/pull/87
Recommend Node.js 18.x
Local testing
---

chore: recommend Node.js 18.x

---

packages/backend/package.json
yarn.lock

N/A
Bumps eslint, and uses caret so that lockfile maintenance can update it's versions
The `yarn build:backend` command is successful
---

chore(deps-dev): bump eslint to 8.31.0

---

packages/backend/package.json
packages/frontend/package.json
packages/infra/package.json
yarn.lock

Follow-up to https://github.com/aws-samples/aws-sdk-js-notes-app/pull/58
Bump typescript to ~4.9.4
Builds are successful
---

chore(deps-dev): bump typescript to ~4.9.4

---

packages/infra/package.json
yarn.lock

N/A
Bumps aws-cdk to 2.110.0
Local testing
---

chore(deps-dev): bump aws-cdk to 2.110.0

---

package.json
packages/frontend/package.json
yarn.lock

https://vitejs.dev/blog/announcing-vite5
Bumps vite to v5.2.7
Local testing
---

chore(deps-dev): bump vite to v5.2.7

---

packages/frontend/package.json

Vite CJS Node API deprecated, and will be removed in Vite 6
Docs: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
Use ESM module in frontend 
Local testing
---

chore(frontend): use ESM module

---

packages/infra/cdk/backend/notes-api.create.ts
packages/infra/cdk/backend/notes-api.delete.ts
packages/infra/cdk/backend/notes-api.get.ts
packages/infra/cdk/backend/notes-api.update.ts

N/A
Remove eslint-disable-next-line no-unused-vars, by doing type imports
Build is successful
---

Remove eslint-disable-next-line no-unused-vars

---

packages/frontend/package.json
packages/infra/package.json
yarn.lock

https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/
Bump typescript to ~5.4.5
Local testing
---

Bump typescript to ~5.4.5

---

README.md

delineated cred locations per OS and added link to AWS docs
Refs: #, if available
What does this implement/fix? Explain your changes.
How was this change tested?
Add any other context about the PR here.
---

docs: specify credentials file and show location in brackets

---

package.json
packages/frontend/package.json
yarn.lock

Fixes https://github.com/aws-samples/aws-sdk-js-notes-app/issues/160
Upgrade Vite from v5 to v6
Local

Bump Vite to v6

---

README.md

`aws-sdk-js-notes-app: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)`
Refs: #, if available
What does this implement/fix? Explain your changes.
When I ran it without `cdk bootstrap` specified, I couldn't deploy it and it states this error. Once I used this command and continued with the README, it deployed properly.
How was this change tested?
Add any other context about the PR here.
---

Add cdk bootstrap cmd before cdk deploy

---

.github/workflows/ci.yml
package.json
packages/frontend/public/worklets/recording-processor.js
packages/frontend/src/libs/getStreamTranscriptionResponse.ts
packages/scripts/populate-frontend-config.js
prettier.config.js
yarn.lock

N/A
Adds GitHub workflow to build+format
CI
---

chore(ci): add GitHub workflow to build+format
